services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017/admin --quiet
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - api_data:/app/output/videos
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/mir_ai?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
        - action: rebuild
          path: ./api/Pipfile.lock
  
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_HOST=${VITE_HOST}
      - VITE_PORT=${VITE_PORT}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    develop:
      watch:
        - action: sync
          path: ./ui
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./ui/package.json

volumes:
  mongodb_data:
  api_data:
